#!/bin/sh

## hyphop ##

cd $(dirname $0)

[ -d /tmp/zero_builder ] || mkdir -p /tmp/zero_builder

TC_SRC=https://github.com/hyphop/pkg/releases/download/mirror
TC_DIR=toolchain-arm_cortex-a8.vfpv3_gcc-5.3.0_musl-1.1.16_eabi
TC_SQUASH=$TC_DIR.squashfs


[ -f ../$TC_SQUASH ] || {
    echo "[i] download $TC_SRC / $TC_SQUASH">&2
    wget $TC_SRC/$TC_SQUASH -O../$TC_SQUASH

}

[ -d ../$TC_DIR ]] || {
    echo "[i] unpack to ../$TC_DIR">&2
    unsquashfs -d ../$TC_DIR ../$TC_SQUASH
}
