#!/bin/sh

## hyphop ##

#flags="-O3 -ffast-math -funroll-loops -Wall -fPIC -DPIC"

#flags="-O3 -ffast-math -funroll-loops -Wall -fPIC -DPIC -mfloat-abi=hard -mfpu=neon -march=armv7-a -mtune=cortex-a9"
flags="-O3 -ffast-math -funroll-loops -Wall -fPIC -DPIC -mfloat-abi=hard -mfpu=neon -march=armv7-a -mtune=cortex-a9"

export ARCH=arm
export CROSS_COMPILE=arm-openwrt-linux-
export bdir=$PWD
export STAGING_DIR=../toolchain-arm_cortex-a8.vfpv3_gcc-5.3.0_musl-1.1.16_eabi

export PATH=$STAGING_DIR/bin/:$PATH

GCC=${CROSS_COMPILE}gcc

CFLAGS=$flags

#rm *.o

#$GCC $CFLAGS -o i2c.o -c i2c.c
$GCC $CFLAGS -o bin/i2c i2c.c

${CROSS_COMPILE}strip bin/i2c